# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    echo $(var1) printed 1
    echo $(var2) printed 2
    echo $(var3) printed 3
  displayName: 'print variables'

- script: bundle exec rake
  displayName: 'bundle exec rake'
